Adds possibility to get meeting invitation by :meeting_id
hintmedia/zoom_rb pull request #56
Opened 2020-09-16 10:27 UTC by nickKolya

Provides endpoint for possibility to get a meeting invitation.
Link to the Zoom API documentation: https://marketplace.zoom.us/docs/api-reference/zoom-api/meetings/meetinginvitation

2020-09-16 10:30 UTC, nickKolya commented
@kyleboe please review

2020-09-17 18:17 UTC, kyleboe requested changes
One small style change. Everything else looks great! Thanks for the contribution and writing tests! 👍

2020-09-17 18:17 UTC, kyleboe commented on lib/zoom/actions/meeting.rb
> +        options.require(%i[meeting_id])
Minor style adjustment (working on making this consistent across the codebase): Only use symbol array literals for arrays of 2 or more. Thanks!

```suggestion
        options.require(:meeting_id)
```

2020-09-17 18:28 UTC, kyleboe approved these changes
Awesome! Thanks for the contribution! 👍

2020-09-17 18:28 UTC, merged

2020-09-28 10:52 UTC, nickKolya commented
Hi @kyleboe! Do you have any plans on when this functionality will be put into the next release update?

2021-06-09 09:40 UTC, nickKolya commented
> Hi @kyleboe! Do you have any plans on when this functionality will be put into the next release update?

Hey @kyleboe, any update on this? 🙂